language: python

script:
    - cp -var textfiles.com public 
    - cp CNAME public/CNAME

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
