language: python

script:
    - mv textfiles.com/* .
    - echo 'textfiles.mirror.strm.sh' CNAME

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
branch: master
