language: python

script:
    - cp -ar textfiles.com public 
    - touch public/.nojekyll
    - echo 'textfiles.mirror.strm.sh' > public/CNAME
    - find . -name "*.1" -exec rename 's/\.1$/\.html/' '{}' \;
    - find . -name '*.html' -exec sed 's/\.1/\.html/g' -i {} +

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public/
  on:
    branch: master
